jobs:
  test_macos:
    name: Test macOS
    runs-on: macOS-14-Sonoma-Medium-Arm64
    steps:
      - type: script
        name: Unit Tests
        script-content: go test -race -count=1 -shuffle=on -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
  test_windows:
    name: Test Windows
    runs-on: Windows-Medium
    steps:
      - type: script
        name: Unit Tests
        script-content: go test -race -count=1 -shuffle=on -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
  test_linux:
    name: Test Linux
    runs-on: Ubuntu-24.04-Large
    parameters:
      env.GOROOT: '/usr/lib/go-1.26'
      env.PATH: '/usr/lib/go-1.26/bin:%env.PATH%'
    steps:
      - type: script
        name: Install Go
        script-content: |
          sudo add-apt-repository -y ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install -y golang-1.26-go
      - type: script
        name: Integration Tests
        script-content: |
          go test -race -count=1 -shuffle=on -v ./... -tags=integration -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-integration.out
      - type: script
        name: Guest Auth Tests
        script-content: |
          TEAMCITY_GUEST=1 go test -race -count=1 -shuffle=on -v ./api/... -tags=guest -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-guest.out
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
      - type: script
        name: Merge Coverage
        script-content: |
          head -1 coverage-integration.out > coverage.out
          tail -n +2 coverage-integration.out >> coverage.out
          tail -n +2 coverage-guest.out >> coverage.out
  test_linux_arm64:
    name: Test Linux ARM64
    runs-on: Ubuntu-24.04-Large-Arm64
    parameters:
      env.GOROOT: '/usr/lib/go-1.26'
      env.PATH: '/usr/lib/go-1.26/bin:%env.PATH%'
    steps:
      - type: script
        name: Install Go
        script-content: |
          sudo add-apt-repository -y ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install -y golang-1.26-go
      - type: script
        name: Integration Tests
        script-content: |
          go test -race -count=1 -shuffle=on -v ./... -tags=integration -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-integration.out
      - type: script
        name: Guest Auth Tests
        script-content: |
          TEAMCITY_GUEST=1 go test -race -count=1 -shuffle=on -v ./api/... -tags=guest -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-guest.out
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
      - type: script
        name: Merge Coverage
        script-content: |
          head -1 coverage-integration.out > coverage.out
          tail -n +2 coverage-integration.out >> coverage.out
          tail -n +2 coverage-guest.out >> coverage.out
  goreleaser:
    name: GoReleaser
    allow-reuse: true
    steps:
      - type: script
        name: Build & Test
        docker-image: goreleaser/goreleaser-pro:latest
        script-content: goreleaser release --snapshot --clean --skip=publish,chocolatey
  lint:
    name: Lint
    allow-reuse: true
    steps:
      - type: script
        name: Lint
        docker-image: golangci/golangci-lint:latest
        script-content: go fmt ./... && golangci-lint run --tests=false ./...
parameters:
  env.TC_INSECURE_SKIP_WARN: '1'
  env.GOPROXY: 'https://proxy.golang.org,direct'
  env.GOFLAGS: '-buildvcs=false'
  env.BRANCH_NAME: '%teamcity.build.branch%'
secrets:
  TEAMCITY_TOKEN: credentialsJSON:c745e669-581a-454e-8984-81f635c1665d
