jobs:
  test_macos:
    name: Test macOS
    steps:
      - type: script
        script-content: go test -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: |
          TC_INSECURE_SKIP_WARN=1 go test -v -tags=acceptance ./acceptance -timeout 10m
    runs-on: macOS-14-Sonoma-Medium-Arm64
  test_windows:
    name: Test Windows
    runs-on: Windows-Medium
    steps:
      - type: script
        script-content: >-
          go test -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: >-
          set TC_INSECURE_SKIP_WARN=1 && go test -v -tags=acceptance ./acceptance -timeout 10m
  test_linux:
    name: Test Linux
    runs-on: Ubuntu-22.04-Medium
    steps:
      - type: script
        name: Install Go
        script-content: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install -y golang-go
      - type: script
        name: Integration Tests
        script-content: |
          export GOPROXY=https://proxy.golang.org,direct GOROOT=/usr/lib/go-1.25
          /usr/lib/go-1.25/bin/go test -v ./... -tags=integration -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-integration.out
      - type: script
        name: Guest Auth Tests
        script-content: |
          export GOPROXY=https://proxy.golang.org,direct GOROOT=/usr/lib/go-1.25
          TEAMCITY_GUEST=1 /usr/lib/go-1.25/bin/go test -v ./api/... -tags=guest -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-guest.out
      - type: script
        name: Acceptance Tests
        script-content: |
          export GOPROXY=https://proxy.golang.org,direct GOROOT=/usr/lib/go-1.25
          TC_INSECURE_SKIP_WARN=1 /usr/lib/go-1.25/bin/go test -v -tags=acceptance ./acceptance -timeout 10m
      - type: script
        name: Merge Coverage
        script-content: |
          head -1 coverage-integration.out > coverage.out
          tail -n +2 coverage-integration.out >> coverage.out
          tail -n +2 coverage-guest.out >> coverage.out
  acceptance:
    name: GoReleaser
    steps:
      - type: script
        docker-image: goreleaser/goreleaser-pro:latest
        name: Build & Test
        script-content: |
          export GOTOOLCHAIN=auto
          goreleaser release --snapshot --clean --skip=publish,chocolatey
  Lint:
    name: Lint
    steps:
      - type: script
        docker-image: golangci/golangci-lint:latest
        name: Lint
        script-content: go fmt ./... && golangci-lint run --tests=false ./...
parameters:
  env.TC_INSECURE_SKIP_WARN: '1'
  env.GOFLAGS: '-buildvcs=false'
  env.BRANCH_NAME: '%teamcity.build.branch%'
