jobs:
  test_macos:
    name: Test macOS
    steps:
      - type: script
        script-content: go test -race -count=1 -shuffle=on -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
    runs-on: macOS-14-Sonoma-Medium-Arm64
  test_windows:
    name: Test Windows
    runs-on: Windows-Medium
    steps:
      - type: script
        script-content: go test -race -count=1 -shuffle=on -v ./... -timeout 15m
      - type: script
        name: Acceptance Tests
        script-content: go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
  test_linux:
    name: Test Linux
    runs-on: Ubuntu-24.04-Large
    steps:
      - type: script
        name: Integration Tests
        script-content: |
          go test -race -count=1 -shuffle=on -v ./... -tags=integration -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-integration.out
      - type: script
        name: Guest Auth Tests
        script-content: |
          TEAMCITY_GUEST=1 go test -race -count=1 -shuffle=on -v ./api/... -tags=guest -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-guest.out
      - type: script
        name: Acceptance Tests
        script-content: |
          go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
      - type: script
        name: Merge Coverage
        script-content: |
          head -1 coverage-integration.out > coverage.out
          tail -n +2 coverage-integration.out >> coverage.out
          tail -n +2 coverage-guest.out >> coverage.out
  test_linux_arm64:
    name: Test Linux ARM64
    runs-on: Ubuntu-24.04-Large-Arm64
    steps:
      - type: script
        name: Integration Tests
        script-content: |
          go test -race -count=1 -shuffle=on -v ./... -tags=integration -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-integration.out
      - type: script
        name: Guest Auth Tests
        script-content: |
          TEAMCITY_GUEST=1 go test -race -count=1 -shuffle=on -v ./api/... -tags=guest -timeout 15m \
            -coverpkg=./... -coverprofile=coverage-guest.out
      - type: script
        name: Acceptance Tests
        script-content: |
          go test -count=1 -shuffle=on -v -tags=acceptance ./acceptance -timeout 10m
      - type: script
        name: Merge Coverage
        script-content: |
          head -1 coverage-integration.out > coverage.out
          tail -n +2 coverage-integration.out >> coverage.out
          tail -n +2 coverage-guest.out >> coverage.out
  acceptance:
    name: GoReleaser
    steps:
      - type: script
        docker-image: goreleaser/goreleaser-pro:latest
        name: Build & Test
        script-content: goreleaser release --snapshot --clean --skip=publish,chocolatey
  Lint:
    name: Lint
    steps:
      - type: script
        docker-image: golangci/golangci-lint:latest
        name: Lint
        script-content: go fmt ./... && golangci-lint run --tests=false ./...
parameters:
  env.TC_INSECURE_SKIP_WARN: '1'
  env.GOTOOLCHAIN: 'auto'
  env.GOFLAGS: '-buildvcs=false'
  env.BRANCH_NAME: '%teamcity.build.branch%'
secrets:
  TEAMCITY_TOKEN: credentialsJSON:c745e669-581a-454e-8984-81f635c1665d
