name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: Run `tc --version` to get this
      placeholder: "v0.2.0"
    validations:
      required: true

  - type: input
    id: tc-version
    attributes:
      label: TeamCity Server Version
      description: Optional - helpful for API-related issues
      placeholder: "2024.12"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely
      placeholder: When I run `tc run start ...` it fails with...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `tc ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy any relevant logs or error messages
      render: shell
