// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/JetBrains/teamcity-cli/internal/api"
	"io"
	"sync"
)

// ClientInterfaceMock is a mock implementation of api.ClientInterface.
//
//	func TestSomethingThatUsesClientInterface(t *testing.T) {
//
//		// make and configure a mocked api.ClientInterface
//		mockedClientInterface := &ClientInterfaceMock{
//			AddBuildTagsFunc: func(buildID string, tags []string) error {
//				panic("mock out the AddBuildTags method")
//			},
//			ApproveQueuedBuildFunc: func(buildID string) error {
//				panic("mock out the ApproveQueuedBuild method")
//			},
//			AuthorizeAgentFunc: func(id int, authorized bool) error {
//				panic("mock out the AuthorizeAgent method")
//			},
//			BuildTypeExistsFunc: func(id string) bool {
//				panic("mock out the BuildTypeExists method")
//			},
//			CancelBuildFunc: func(buildID string, comment string) error {
//				panic("mock out the CancelBuild method")
//			},
//			CheckVersionFunc: func() error {
//				panic("mock out the CheckVersion method")
//			},
//			CreateAPITokenFunc: func(name string) (*api.Token, error) {
//				panic("mock out the CreateAPIToken method")
//			},
//			CreateBuildStepFunc: func(buildTypeID string, step api.BuildStep) error {
//				panic("mock out the CreateBuildStep method")
//			},
//			CreateBuildTypeFunc: func(projectID string, req api.CreateBuildTypeRequest) (*api.BuildType, error) {
//				panic("mock out the CreateBuildType method")
//			},
//			CreateProjectFunc: func(req api.CreateProjectRequest) (*api.Project, error) {
//				panic("mock out the CreateProject method")
//			},
//			CreateSecureTokenFunc: func(projectID string, value string) (string, error) {
//				panic("mock out the CreateSecureToken method")
//			},
//			CreateUserFunc: func(req api.CreateUserRequest) (*api.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			DeleteAPITokenFunc: func(name string) error {
//				panic("mock out the DeleteAPIToken method")
//			},
//			DeleteBuildCommentFunc: func(buildID string) error {
//				panic("mock out the DeleteBuildComment method")
//			},
//			DeleteBuildTypeParameterFunc: func(buildTypeID string, name string) error {
//				panic("mock out the DeleteBuildTypeParameter method")
//			},
//			DeleteProjectParameterFunc: func(projectID string, name string) error {
//				panic("mock out the DeleteProjectParameter method")
//			},
//			DownloadArtifactFunc: func(buildID string, artifactPath string) ([]byte, error) {
//				panic("mock out the DownloadArtifact method")
//			},
//			GetAgentsFunc: func(opts api.AgentsOptions) (*api.AgentList, error) {
//				panic("mock out the GetAgents method")
//			},
//			GetArtifactsFunc: func(buildID string) (*api.Artifacts, error) {
//				panic("mock out the GetArtifacts method")
//			},
//			GetBuildFunc: func(ref string) (*api.Build, error) {
//				panic("mock out the GetBuild method")
//			},
//			GetBuildChangesFunc: func(buildID string) (*api.ChangeList, error) {
//				panic("mock out the GetBuildChanges method")
//			},
//			GetBuildCommentFunc: func(buildID string) (string, error) {
//				panic("mock out the GetBuildComment method")
//			},
//			GetBuildLogFunc: func(buildID string) (string, error) {
//				panic("mock out the GetBuildLog method")
//			},
//			GetBuildQueueFunc: func(opts api.QueueOptions) (*api.BuildQueue, error) {
//				panic("mock out the GetBuildQueue method")
//			},
//			GetBuildTagsFunc: func(buildID string) (*api.TagList, error) {
//				panic("mock out the GetBuildTags method")
//			},
//			GetBuildTestsFunc: func(buildID string, failedOnly bool, limit int) (*api.TestOccurrences, error) {
//				panic("mock out the GetBuildTests method")
//			},
//			GetBuildTypeFunc: func(id string) (*api.BuildType, error) {
//				panic("mock out the GetBuildType method")
//			},
//			GetBuildTypeParameterFunc: func(buildTypeID string, name string) (*api.Parameter, error) {
//				panic("mock out the GetBuildTypeParameter method")
//			},
//			GetBuildTypeParametersFunc: func(buildTypeID string) (*api.ParameterList, error) {
//				panic("mock out the GetBuildTypeParameters method")
//			},
//			GetBuildTypesFunc: func(opts api.BuildTypesOptions) (*api.BuildTypeList, error) {
//				panic("mock out the GetBuildTypes method")
//			},
//			GetBuildsFunc: func(opts api.BuildsOptions) (*api.BuildList, error) {
//				panic("mock out the GetBuilds method")
//			},
//			GetCurrentUserFunc: func() (*api.User, error) {
//				panic("mock out the GetCurrentUser method")
//			},
//			GetParameterValueFunc: func(path string) (string, error) {
//				panic("mock out the GetParameterValue method")
//			},
//			GetProjectFunc: func(id string) (*api.Project, error) {
//				panic("mock out the GetProject method")
//			},
//			GetProjectParameterFunc: func(projectID string, name string) (*api.Parameter, error) {
//				panic("mock out the GetProjectParameter method")
//			},
//			GetProjectParametersFunc: func(projectID string) (*api.ParameterList, error) {
//				panic("mock out the GetProjectParameters method")
//			},
//			GetProjectsFunc: func(opts api.ProjectsOptions) (*api.ProjectList, error) {
//				panic("mock out the GetProjects method")
//			},
//			GetQueuedBuildApprovalInfoFunc: func(buildID string) (*api.ApprovalInfo, error) {
//				panic("mock out the GetQueuedBuildApprovalInfo method")
//			},
//			GetSecureValueFunc: func(projectID string, token string) (string, error) {
//				panic("mock out the GetSecureValue method")
//			},
//			GetServerFunc: func() (*api.Server, error) {
//				panic("mock out the GetServer method")
//			},
//			GetUserFunc: func(username string) (*api.User, error) {
//				panic("mock out the GetUser method")
//			},
//			MoveQueuedBuildToTopFunc: func(buildID string) error {
//				panic("mock out the MoveQueuedBuildToTop method")
//			},
//			PinBuildFunc: func(buildID string, comment string) error {
//				panic("mock out the PinBuild method")
//			},
//			ProjectExistsFunc: func(id string) bool {
//				panic("mock out the ProjectExists method")
//			},
//			RawRequestFunc: func(method string, path string, body io.Reader, headers map[string]string) (*api.RawResponse, error) {
//				panic("mock out the RawRequest method")
//			},
//			RemoveBuildTagFunc: func(buildID string, tag string) error {
//				panic("mock out the RemoveBuildTag method")
//			},
//			RemoveFromQueueFunc: func(id string) error {
//				panic("mock out the RemoveFromQueue method")
//			},
//			ResolveBuildIDFunc: func(ref string) (string, error) {
//				panic("mock out the ResolveBuildID method")
//			},
//			RunBuildFunc: func(buildTypeID string, opts api.RunBuildOptions) (*api.Build, error) {
//				panic("mock out the RunBuild method")
//			},
//			ServerVersionFunc: func() (*api.Server, error) {
//				panic("mock out the ServerVersion method")
//			},
//			SetBuildCommentFunc: func(buildID string, comment string) error {
//				panic("mock out the SetBuildComment method")
//			},
//			SetBuildTypeParameterFunc: func(buildTypeID string, name string, value string, secure bool) error {
//				panic("mock out the SetBuildTypeParameter method")
//			},
//			SetBuildTypePausedFunc: func(id string, paused bool) error {
//				panic("mock out the SetBuildTypePaused method")
//			},
//			SetBuildTypeSettingFunc: func(buildTypeID string, setting string, value string) error {
//				panic("mock out the SetBuildTypeSetting method")
//			},
//			SetProjectParameterFunc: func(projectID string, name string, value string, secure bool) error {
//				panic("mock out the SetProjectParameter method")
//			},
//			SetQueuedBuildPositionFunc: func(buildID string, position int) error {
//				panic("mock out the SetQueuedBuildPosition method")
//			},
//			SupportsFeatureFunc: func(feature string) bool {
//				panic("mock out the SupportsFeature method")
//			},
//			UnpinBuildFunc: func(buildID string) error {
//				panic("mock out the UnpinBuild method")
//			},
//			UserExistsFunc: func(username string) bool {
//				panic("mock out the UserExists method")
//			},
//		}
//
//		// use mockedClientInterface in code that requires api.ClientInterface
//		// and then make assertions.
//
//	}
type ClientInterfaceMock struct {
	// AddBuildTagsFunc mocks the AddBuildTags method.
	AddBuildTagsFunc func(buildID string, tags []string) error

	// ApproveQueuedBuildFunc mocks the ApproveQueuedBuild method.
	ApproveQueuedBuildFunc func(buildID string) error

	// AuthorizeAgentFunc mocks the AuthorizeAgent method.
	AuthorizeAgentFunc func(id int, authorized bool) error

	// BuildTypeExistsFunc mocks the BuildTypeExists method.
	BuildTypeExistsFunc func(id string) bool

	// CancelBuildFunc mocks the CancelBuild method.
	CancelBuildFunc func(buildID string, comment string) error

	// CheckVersionFunc mocks the CheckVersion method.
	CheckVersionFunc func() error

	// CreateAPITokenFunc mocks the CreateAPIToken method.
	CreateAPITokenFunc func(name string) (*api.Token, error)

	// CreateBuildStepFunc mocks the CreateBuildStep method.
	CreateBuildStepFunc func(buildTypeID string, step api.BuildStep) error

	// CreateBuildTypeFunc mocks the CreateBuildType method.
	CreateBuildTypeFunc func(projectID string, req api.CreateBuildTypeRequest) (*api.BuildType, error)

	// CreateProjectFunc mocks the CreateProject method.
	CreateProjectFunc func(req api.CreateProjectRequest) (*api.Project, error)

	// CreateSecureTokenFunc mocks the CreateSecureToken method.
	CreateSecureTokenFunc func(projectID string, value string) (string, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(req api.CreateUserRequest) (*api.User, error)

	// DeleteAPITokenFunc mocks the DeleteAPIToken method.
	DeleteAPITokenFunc func(name string) error

	// DeleteBuildCommentFunc mocks the DeleteBuildComment method.
	DeleteBuildCommentFunc func(buildID string) error

	// DeleteBuildTypeParameterFunc mocks the DeleteBuildTypeParameter method.
	DeleteBuildTypeParameterFunc func(buildTypeID string, name string) error

	// DeleteProjectParameterFunc mocks the DeleteProjectParameter method.
	DeleteProjectParameterFunc func(projectID string, name string) error

	// DownloadArtifactFunc mocks the DownloadArtifact method.
	DownloadArtifactFunc func(buildID string, artifactPath string) ([]byte, error)

	// GetAgentsFunc mocks the GetAgents method.
	GetAgentsFunc func(opts api.AgentsOptions) (*api.AgentList, error)

	// GetArtifactsFunc mocks the GetArtifacts method.
	GetArtifactsFunc func(buildID string) (*api.Artifacts, error)

	// GetBuildFunc mocks the GetBuild method.
	GetBuildFunc func(ref string) (*api.Build, error)

	// GetBuildChangesFunc mocks the GetBuildChanges method.
	GetBuildChangesFunc func(buildID string) (*api.ChangeList, error)

	// GetBuildCommentFunc mocks the GetBuildComment method.
	GetBuildCommentFunc func(buildID string) (string, error)

	// GetBuildLogFunc mocks the GetBuildLog method.
	GetBuildLogFunc func(buildID string) (string, error)

	// GetBuildQueueFunc mocks the GetBuildQueue method.
	GetBuildQueueFunc func(opts api.QueueOptions) (*api.BuildQueue, error)

	// GetBuildTagsFunc mocks the GetBuildTags method.
	GetBuildTagsFunc func(buildID string) (*api.TagList, error)

	// GetBuildTestsFunc mocks the GetBuildTests method.
	GetBuildTestsFunc func(buildID string, failedOnly bool, limit int) (*api.TestOccurrences, error)

	// GetBuildTypeFunc mocks the GetBuildType method.
	GetBuildTypeFunc func(id string) (*api.BuildType, error)

	// GetBuildTypeParameterFunc mocks the GetBuildTypeParameter method.
	GetBuildTypeParameterFunc func(buildTypeID string, name string) (*api.Parameter, error)

	// GetBuildTypeParametersFunc mocks the GetBuildTypeParameters method.
	GetBuildTypeParametersFunc func(buildTypeID string) (*api.ParameterList, error)

	// GetBuildTypesFunc mocks the GetBuildTypes method.
	GetBuildTypesFunc func(opts api.BuildTypesOptions) (*api.BuildTypeList, error)

	// GetBuildsFunc mocks the GetBuilds method.
	GetBuildsFunc func(opts api.BuildsOptions) (*api.BuildList, error)

	// GetCurrentUserFunc mocks the GetCurrentUser method.
	GetCurrentUserFunc func() (*api.User, error)

	// GetParameterValueFunc mocks the GetParameterValue method.
	GetParameterValueFunc func(path string) (string, error)

	// GetProjectFunc mocks the GetProject method.
	GetProjectFunc func(id string) (*api.Project, error)

	// GetProjectParameterFunc mocks the GetProjectParameter method.
	GetProjectParameterFunc func(projectID string, name string) (*api.Parameter, error)

	// GetProjectParametersFunc mocks the GetProjectParameters method.
	GetProjectParametersFunc func(projectID string) (*api.ParameterList, error)

	// GetProjectsFunc mocks the GetProjects method.
	GetProjectsFunc func(opts api.ProjectsOptions) (*api.ProjectList, error)

	// GetQueuedBuildApprovalInfoFunc mocks the GetQueuedBuildApprovalInfo method.
	GetQueuedBuildApprovalInfoFunc func(buildID string) (*api.ApprovalInfo, error)

	// GetSecureValueFunc mocks the GetSecureValue method.
	GetSecureValueFunc func(projectID string, token string) (string, error)

	// GetServerFunc mocks the GetServer method.
	GetServerFunc func() (*api.Server, error)

	// GetUserFunc mocks the GetUser method.
	GetUserFunc func(username string) (*api.User, error)

	// MoveQueuedBuildToTopFunc mocks the MoveQueuedBuildToTop method.
	MoveQueuedBuildToTopFunc func(buildID string) error

	// PinBuildFunc mocks the PinBuild method.
	PinBuildFunc func(buildID string, comment string) error

	// ProjectExistsFunc mocks the ProjectExists method.
	ProjectExistsFunc func(id string) bool

	// RawRequestFunc mocks the RawRequest method.
	RawRequestFunc func(method string, path string, body io.Reader, headers map[string]string) (*api.RawResponse, error)

	// RemoveBuildTagFunc mocks the RemoveBuildTag method.
	RemoveBuildTagFunc func(buildID string, tag string) error

	// RemoveFromQueueFunc mocks the RemoveFromQueue method.
	RemoveFromQueueFunc func(id string) error

	// ResolveBuildIDFunc mocks the ResolveBuildID method.
	ResolveBuildIDFunc func(ref string) (string, error)

	// RunBuildFunc mocks the RunBuild method.
	RunBuildFunc func(buildTypeID string, opts api.RunBuildOptions) (*api.Build, error)

	// ServerVersionFunc mocks the ServerVersion method.
	ServerVersionFunc func() (*api.Server, error)

	// SetBuildCommentFunc mocks the SetBuildComment method.
	SetBuildCommentFunc func(buildID string, comment string) error

	// SetBuildTypeParameterFunc mocks the SetBuildTypeParameter method.
	SetBuildTypeParameterFunc func(buildTypeID string, name string, value string, secure bool) error

	// SetBuildTypePausedFunc mocks the SetBuildTypePaused method.
	SetBuildTypePausedFunc func(id string, paused bool) error

	// SetBuildTypeSettingFunc mocks the SetBuildTypeSetting method.
	SetBuildTypeSettingFunc func(buildTypeID string, setting string, value string) error

	// SetProjectParameterFunc mocks the SetProjectParameter method.
	SetProjectParameterFunc func(projectID string, name string, value string, secure bool) error

	// SetQueuedBuildPositionFunc mocks the SetQueuedBuildPosition method.
	SetQueuedBuildPositionFunc func(buildID string, position int) error

	// SupportsFeatureFunc mocks the SupportsFeature method.
	SupportsFeatureFunc func(feature string) bool

	// UnpinBuildFunc mocks the UnpinBuild method.
	UnpinBuildFunc func(buildID string) error

	// UserExistsFunc mocks the UserExists method.
	UserExistsFunc func(username string) bool

	// calls tracks calls to the methods.
	calls struct {
		// AddBuildTags holds details about calls to the AddBuildTags method.
		AddBuildTags []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Tags is the tags argument value.
			Tags []string
		}
		// ApproveQueuedBuild holds details about calls to the ApproveQueuedBuild method.
		ApproveQueuedBuild []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// AuthorizeAgent holds details about calls to the AuthorizeAgent method.
		AuthorizeAgent []struct {
			// ID is the id argument value.
			ID int
			// Authorized is the authorized argument value.
			Authorized bool
		}
		// BuildTypeExists holds details about calls to the BuildTypeExists method.
		BuildTypeExists []struct {
			// ID is the id argument value.
			ID string
		}
		// CancelBuild holds details about calls to the CancelBuild method.
		CancelBuild []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Comment is the comment argument value.
			Comment string
		}
		// CheckVersion holds details about calls to the CheckVersion method.
		CheckVersion []struct {
		}
		// CreateAPIToken holds details about calls to the CreateAPIToken method.
		CreateAPIToken []struct {
			// Name is the name argument value.
			Name string
		}
		// CreateBuildStep holds details about calls to the CreateBuildStep method.
		CreateBuildStep []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Step is the step argument value.
			Step api.BuildStep
		}
		// CreateBuildType holds details about calls to the CreateBuildType method.
		CreateBuildType []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Req is the req argument value.
			Req api.CreateBuildTypeRequest
		}
		// CreateProject holds details about calls to the CreateProject method.
		CreateProject []struct {
			// Req is the req argument value.
			Req api.CreateProjectRequest
		}
		// CreateSecureToken holds details about calls to the CreateSecureToken method.
		CreateSecureToken []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Value is the value argument value.
			Value string
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Req is the req argument value.
			Req api.CreateUserRequest
		}
		// DeleteAPIToken holds details about calls to the DeleteAPIToken method.
		DeleteAPIToken []struct {
			// Name is the name argument value.
			Name string
		}
		// DeleteBuildComment holds details about calls to the DeleteBuildComment method.
		DeleteBuildComment []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// DeleteBuildTypeParameter holds details about calls to the DeleteBuildTypeParameter method.
		DeleteBuildTypeParameter []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Name is the name argument value.
			Name string
		}
		// DeleteProjectParameter holds details about calls to the DeleteProjectParameter method.
		DeleteProjectParameter []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Name is the name argument value.
			Name string
		}
		// DownloadArtifact holds details about calls to the DownloadArtifact method.
		DownloadArtifact []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// ArtifactPath is the artifactPath argument value.
			ArtifactPath string
		}
		// GetAgents holds details about calls to the GetAgents method.
		GetAgents []struct {
			// Opts is the opts argument value.
			Opts api.AgentsOptions
		}
		// GetArtifacts holds details about calls to the GetArtifacts method.
		GetArtifacts []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetBuild holds details about calls to the GetBuild method.
		GetBuild []struct {
			// Ref is the ref argument value.
			Ref string
		}
		// GetBuildChanges holds details about calls to the GetBuildChanges method.
		GetBuildChanges []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetBuildComment holds details about calls to the GetBuildComment method.
		GetBuildComment []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetBuildLog holds details about calls to the GetBuildLog method.
		GetBuildLog []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetBuildQueue holds details about calls to the GetBuildQueue method.
		GetBuildQueue []struct {
			// Opts is the opts argument value.
			Opts api.QueueOptions
		}
		// GetBuildTags holds details about calls to the GetBuildTags method.
		GetBuildTags []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetBuildTests holds details about calls to the GetBuildTests method.
		GetBuildTests []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// FailedOnly is the failedOnly argument value.
			FailedOnly bool
			// Limit is the limit argument value.
			Limit int
		}
		// GetBuildType holds details about calls to the GetBuildType method.
		GetBuildType []struct {
			// ID is the id argument value.
			ID string
		}
		// GetBuildTypeParameter holds details about calls to the GetBuildTypeParameter method.
		GetBuildTypeParameter []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Name is the name argument value.
			Name string
		}
		// GetBuildTypeParameters holds details about calls to the GetBuildTypeParameters method.
		GetBuildTypeParameters []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
		}
		// GetBuildTypes holds details about calls to the GetBuildTypes method.
		GetBuildTypes []struct {
			// Opts is the opts argument value.
			Opts api.BuildTypesOptions
		}
		// GetBuilds holds details about calls to the GetBuilds method.
		GetBuilds []struct {
			// Opts is the opts argument value.
			Opts api.BuildsOptions
		}
		// GetCurrentUser holds details about calls to the GetCurrentUser method.
		GetCurrentUser []struct {
		}
		// GetParameterValue holds details about calls to the GetParameterValue method.
		GetParameterValue []struct {
			// Path is the path argument value.
			Path string
		}
		// GetProject holds details about calls to the GetProject method.
		GetProject []struct {
			// ID is the id argument value.
			ID string
		}
		// GetProjectParameter holds details about calls to the GetProjectParameter method.
		GetProjectParameter []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Name is the name argument value.
			Name string
		}
		// GetProjectParameters holds details about calls to the GetProjectParameters method.
		GetProjectParameters []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
		}
		// GetProjects holds details about calls to the GetProjects method.
		GetProjects []struct {
			// Opts is the opts argument value.
			Opts api.ProjectsOptions
		}
		// GetQueuedBuildApprovalInfo holds details about calls to the GetQueuedBuildApprovalInfo method.
		GetQueuedBuildApprovalInfo []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// GetSecureValue holds details about calls to the GetSecureValue method.
		GetSecureValue []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Token is the token argument value.
			Token string
		}
		// GetServer holds details about calls to the GetServer method.
		GetServer []struct {
		}
		// GetUser holds details about calls to the GetUser method.
		GetUser []struct {
			// Username is the username argument value.
			Username string
		}
		// MoveQueuedBuildToTop holds details about calls to the MoveQueuedBuildToTop method.
		MoveQueuedBuildToTop []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// PinBuild holds details about calls to the PinBuild method.
		PinBuild []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Comment is the comment argument value.
			Comment string
		}
		// ProjectExists holds details about calls to the ProjectExists method.
		ProjectExists []struct {
			// ID is the id argument value.
			ID string
		}
		// RawRequest holds details about calls to the RawRequest method.
		RawRequest []struct {
			// Method is the method argument value.
			Method string
			// Path is the path argument value.
			Path string
			// Body is the body argument value.
			Body io.Reader
			// Headers is the headers argument value.
			Headers map[string]string
		}
		// RemoveBuildTag holds details about calls to the RemoveBuildTag method.
		RemoveBuildTag []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Tag is the tag argument value.
			Tag string
		}
		// RemoveFromQueue holds details about calls to the RemoveFromQueue method.
		RemoveFromQueue []struct {
			// ID is the id argument value.
			ID string
		}
		// ResolveBuildID holds details about calls to the ResolveBuildID method.
		ResolveBuildID []struct {
			// Ref is the ref argument value.
			Ref string
		}
		// RunBuild holds details about calls to the RunBuild method.
		RunBuild []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Opts is the opts argument value.
			Opts api.RunBuildOptions
		}
		// ServerVersion holds details about calls to the ServerVersion method.
		ServerVersion []struct {
		}
		// SetBuildComment holds details about calls to the SetBuildComment method.
		SetBuildComment []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Comment is the comment argument value.
			Comment string
		}
		// SetBuildTypeParameter holds details about calls to the SetBuildTypeParameter method.
		SetBuildTypeParameter []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Name is the name argument value.
			Name string
			// Value is the value argument value.
			Value string
			// Secure is the secure argument value.
			Secure bool
		}
		// SetBuildTypePaused holds details about calls to the SetBuildTypePaused method.
		SetBuildTypePaused []struct {
			// ID is the id argument value.
			ID string
			// Paused is the paused argument value.
			Paused bool
		}
		// SetBuildTypeSetting holds details about calls to the SetBuildTypeSetting method.
		SetBuildTypeSetting []struct {
			// BuildTypeID is the buildTypeID argument value.
			BuildTypeID string
			// Setting is the setting argument value.
			Setting string
			// Value is the value argument value.
			Value string
		}
		// SetProjectParameter holds details about calls to the SetProjectParameter method.
		SetProjectParameter []struct {
			// ProjectID is the projectID argument value.
			ProjectID string
			// Name is the name argument value.
			Name string
			// Value is the value argument value.
			Value string
			// Secure is the secure argument value.
			Secure bool
		}
		// SetQueuedBuildPosition holds details about calls to the SetQueuedBuildPosition method.
		SetQueuedBuildPosition []struct {
			// BuildID is the buildID argument value.
			BuildID string
			// Position is the position argument value.
			Position int
		}
		// SupportsFeature holds details about calls to the SupportsFeature method.
		SupportsFeature []struct {
			// Feature is the feature argument value.
			Feature string
		}
		// UnpinBuild holds details about calls to the UnpinBuild method.
		UnpinBuild []struct {
			// BuildID is the buildID argument value.
			BuildID string
		}
		// UserExists holds details about calls to the UserExists method.
		UserExists []struct {
			// Username is the username argument value.
			Username string
		}
	}
	lockAddBuildTags               sync.RWMutex
	lockApproveQueuedBuild         sync.RWMutex
	lockAuthorizeAgent             sync.RWMutex
	lockBuildTypeExists            sync.RWMutex
	lockCancelBuild                sync.RWMutex
	lockCheckVersion               sync.RWMutex
	lockCreateAPIToken             sync.RWMutex
	lockCreateBuildStep            sync.RWMutex
	lockCreateBuildType            sync.RWMutex
	lockCreateProject              sync.RWMutex
	lockCreateSecureToken          sync.RWMutex
	lockCreateUser                 sync.RWMutex
	lockDeleteAPIToken             sync.RWMutex
	lockDeleteBuildComment         sync.RWMutex
	lockDeleteBuildTypeParameter   sync.RWMutex
	lockDeleteProjectParameter     sync.RWMutex
	lockDownloadArtifact           sync.RWMutex
	lockGetAgents                  sync.RWMutex
	lockGetArtifacts               sync.RWMutex
	lockGetBuild                   sync.RWMutex
	lockGetBuildChanges            sync.RWMutex
	lockGetBuildComment            sync.RWMutex
	lockGetBuildLog                sync.RWMutex
	lockGetBuildQueue              sync.RWMutex
	lockGetBuildTags               sync.RWMutex
	lockGetBuildTests              sync.RWMutex
	lockGetBuildType               sync.RWMutex
	lockGetBuildTypeParameter      sync.RWMutex
	lockGetBuildTypeParameters     sync.RWMutex
	lockGetBuildTypes              sync.RWMutex
	lockGetBuilds                  sync.RWMutex
	lockGetCurrentUser             sync.RWMutex
	lockGetParameterValue          sync.RWMutex
	lockGetProject                 sync.RWMutex
	lockGetProjectParameter        sync.RWMutex
	lockGetProjectParameters       sync.RWMutex
	lockGetProjects                sync.RWMutex
	lockGetQueuedBuildApprovalInfo sync.RWMutex
	lockGetSecureValue             sync.RWMutex
	lockGetServer                  sync.RWMutex
	lockGetUser                    sync.RWMutex
	lockMoveQueuedBuildToTop       sync.RWMutex
	lockPinBuild                   sync.RWMutex
	lockProjectExists              sync.RWMutex
	lockRawRequest                 sync.RWMutex
	lockRemoveBuildTag             sync.RWMutex
	lockRemoveFromQueue            sync.RWMutex
	lockResolveBuildID             sync.RWMutex
	lockRunBuild                   sync.RWMutex
	lockServerVersion              sync.RWMutex
	lockSetBuildComment            sync.RWMutex
	lockSetBuildTypeParameter      sync.RWMutex
	lockSetBuildTypePaused         sync.RWMutex
	lockSetBuildTypeSetting        sync.RWMutex
	lockSetProjectParameter        sync.RWMutex
	lockSetQueuedBuildPosition     sync.RWMutex
	lockSupportsFeature            sync.RWMutex
	lockUnpinBuild                 sync.RWMutex
	lockUserExists                 sync.RWMutex
}

// AddBuildTags calls AddBuildTagsFunc.
func (mock *ClientInterfaceMock) AddBuildTags(buildID string, tags []string) error {
	if mock.AddBuildTagsFunc == nil {
		panic("ClientInterfaceMock.AddBuildTagsFunc: method is nil but ClientInterface.AddBuildTags was just called")
	}
	callInfo := struct {
		BuildID string
		Tags    []string
	}{
		BuildID: buildID,
		Tags:    tags,
	}
	mock.lockAddBuildTags.Lock()
	mock.calls.AddBuildTags = append(mock.calls.AddBuildTags, callInfo)
	mock.lockAddBuildTags.Unlock()
	return mock.AddBuildTagsFunc(buildID, tags)
}

// AddBuildTagsCalls gets all the calls that were made to AddBuildTags.
// Check the length with:
//
//	len(mockedClientInterface.AddBuildTagsCalls())
func (mock *ClientInterfaceMock) AddBuildTagsCalls() []struct {
	BuildID string
	Tags    []string
} {
	var calls []struct {
		BuildID string
		Tags    []string
	}
	mock.lockAddBuildTags.RLock()
	calls = mock.calls.AddBuildTags
	mock.lockAddBuildTags.RUnlock()
	return calls
}

// ApproveQueuedBuild calls ApproveQueuedBuildFunc.
func (mock *ClientInterfaceMock) ApproveQueuedBuild(buildID string) error {
	if mock.ApproveQueuedBuildFunc == nil {
		panic("ClientInterfaceMock.ApproveQueuedBuildFunc: method is nil but ClientInterface.ApproveQueuedBuild was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockApproveQueuedBuild.Lock()
	mock.calls.ApproveQueuedBuild = append(mock.calls.ApproveQueuedBuild, callInfo)
	mock.lockApproveQueuedBuild.Unlock()
	return mock.ApproveQueuedBuildFunc(buildID)
}

// ApproveQueuedBuildCalls gets all the calls that were made to ApproveQueuedBuild.
// Check the length with:
//
//	len(mockedClientInterface.ApproveQueuedBuildCalls())
func (mock *ClientInterfaceMock) ApproveQueuedBuildCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockApproveQueuedBuild.RLock()
	calls = mock.calls.ApproveQueuedBuild
	mock.lockApproveQueuedBuild.RUnlock()
	return calls
}

// AuthorizeAgent calls AuthorizeAgentFunc.
func (mock *ClientInterfaceMock) AuthorizeAgent(id int, authorized bool) error {
	if mock.AuthorizeAgentFunc == nil {
		panic("ClientInterfaceMock.AuthorizeAgentFunc: method is nil but ClientInterface.AuthorizeAgent was just called")
	}
	callInfo := struct {
		ID         int
		Authorized bool
	}{
		ID:         id,
		Authorized: authorized,
	}
	mock.lockAuthorizeAgent.Lock()
	mock.calls.AuthorizeAgent = append(mock.calls.AuthorizeAgent, callInfo)
	mock.lockAuthorizeAgent.Unlock()
	return mock.AuthorizeAgentFunc(id, authorized)
}

// AuthorizeAgentCalls gets all the calls that were made to AuthorizeAgent.
// Check the length with:
//
//	len(mockedClientInterface.AuthorizeAgentCalls())
func (mock *ClientInterfaceMock) AuthorizeAgentCalls() []struct {
	ID         int
	Authorized bool
} {
	var calls []struct {
		ID         int
		Authorized bool
	}
	mock.lockAuthorizeAgent.RLock()
	calls = mock.calls.AuthorizeAgent
	mock.lockAuthorizeAgent.RUnlock()
	return calls
}

// BuildTypeExists calls BuildTypeExistsFunc.
func (mock *ClientInterfaceMock) BuildTypeExists(id string) bool {
	if mock.BuildTypeExistsFunc == nil {
		panic("ClientInterfaceMock.BuildTypeExistsFunc: method is nil but ClientInterface.BuildTypeExists was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockBuildTypeExists.Lock()
	mock.calls.BuildTypeExists = append(mock.calls.BuildTypeExists, callInfo)
	mock.lockBuildTypeExists.Unlock()
	return mock.BuildTypeExistsFunc(id)
}

// BuildTypeExistsCalls gets all the calls that were made to BuildTypeExists.
// Check the length with:
//
//	len(mockedClientInterface.BuildTypeExistsCalls())
func (mock *ClientInterfaceMock) BuildTypeExistsCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockBuildTypeExists.RLock()
	calls = mock.calls.BuildTypeExists
	mock.lockBuildTypeExists.RUnlock()
	return calls
}

// CancelBuild calls CancelBuildFunc.
func (mock *ClientInterfaceMock) CancelBuild(buildID string, comment string) error {
	if mock.CancelBuildFunc == nil {
		panic("ClientInterfaceMock.CancelBuildFunc: method is nil but ClientInterface.CancelBuild was just called")
	}
	callInfo := struct {
		BuildID string
		Comment string
	}{
		BuildID: buildID,
		Comment: comment,
	}
	mock.lockCancelBuild.Lock()
	mock.calls.CancelBuild = append(mock.calls.CancelBuild, callInfo)
	mock.lockCancelBuild.Unlock()
	return mock.CancelBuildFunc(buildID, comment)
}

// CancelBuildCalls gets all the calls that were made to CancelBuild.
// Check the length with:
//
//	len(mockedClientInterface.CancelBuildCalls())
func (mock *ClientInterfaceMock) CancelBuildCalls() []struct {
	BuildID string
	Comment string
} {
	var calls []struct {
		BuildID string
		Comment string
	}
	mock.lockCancelBuild.RLock()
	calls = mock.calls.CancelBuild
	mock.lockCancelBuild.RUnlock()
	return calls
}

// CheckVersion calls CheckVersionFunc.
func (mock *ClientInterfaceMock) CheckVersion() error {
	if mock.CheckVersionFunc == nil {
		panic("ClientInterfaceMock.CheckVersionFunc: method is nil but ClientInterface.CheckVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCheckVersion.Lock()
	mock.calls.CheckVersion = append(mock.calls.CheckVersion, callInfo)
	mock.lockCheckVersion.Unlock()
	return mock.CheckVersionFunc()
}

// CheckVersionCalls gets all the calls that were made to CheckVersion.
// Check the length with:
//
//	len(mockedClientInterface.CheckVersionCalls())
func (mock *ClientInterfaceMock) CheckVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckVersion.RLock()
	calls = mock.calls.CheckVersion
	mock.lockCheckVersion.RUnlock()
	return calls
}

// CreateAPIToken calls CreateAPITokenFunc.
func (mock *ClientInterfaceMock) CreateAPIToken(name string) (*api.Token, error) {
	if mock.CreateAPITokenFunc == nil {
		panic("ClientInterfaceMock.CreateAPITokenFunc: method is nil but ClientInterface.CreateAPIToken was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockCreateAPIToken.Lock()
	mock.calls.CreateAPIToken = append(mock.calls.CreateAPIToken, callInfo)
	mock.lockCreateAPIToken.Unlock()
	return mock.CreateAPITokenFunc(name)
}

// CreateAPITokenCalls gets all the calls that were made to CreateAPIToken.
// Check the length with:
//
//	len(mockedClientInterface.CreateAPITokenCalls())
func (mock *ClientInterfaceMock) CreateAPITokenCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockCreateAPIToken.RLock()
	calls = mock.calls.CreateAPIToken
	mock.lockCreateAPIToken.RUnlock()
	return calls
}

// CreateBuildStep calls CreateBuildStepFunc.
func (mock *ClientInterfaceMock) CreateBuildStep(buildTypeID string, step api.BuildStep) error {
	if mock.CreateBuildStepFunc == nil {
		panic("ClientInterfaceMock.CreateBuildStepFunc: method is nil but ClientInterface.CreateBuildStep was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Step        api.BuildStep
	}{
		BuildTypeID: buildTypeID,
		Step:        step,
	}
	mock.lockCreateBuildStep.Lock()
	mock.calls.CreateBuildStep = append(mock.calls.CreateBuildStep, callInfo)
	mock.lockCreateBuildStep.Unlock()
	return mock.CreateBuildStepFunc(buildTypeID, step)
}

// CreateBuildStepCalls gets all the calls that were made to CreateBuildStep.
// Check the length with:
//
//	len(mockedClientInterface.CreateBuildStepCalls())
func (mock *ClientInterfaceMock) CreateBuildStepCalls() []struct {
	BuildTypeID string
	Step        api.BuildStep
} {
	var calls []struct {
		BuildTypeID string
		Step        api.BuildStep
	}
	mock.lockCreateBuildStep.RLock()
	calls = mock.calls.CreateBuildStep
	mock.lockCreateBuildStep.RUnlock()
	return calls
}

// CreateBuildType calls CreateBuildTypeFunc.
func (mock *ClientInterfaceMock) CreateBuildType(projectID string, req api.CreateBuildTypeRequest) (*api.BuildType, error) {
	if mock.CreateBuildTypeFunc == nil {
		panic("ClientInterfaceMock.CreateBuildTypeFunc: method is nil but ClientInterface.CreateBuildType was just called")
	}
	callInfo := struct {
		ProjectID string
		Req       api.CreateBuildTypeRequest
	}{
		ProjectID: projectID,
		Req:       req,
	}
	mock.lockCreateBuildType.Lock()
	mock.calls.CreateBuildType = append(mock.calls.CreateBuildType, callInfo)
	mock.lockCreateBuildType.Unlock()
	return mock.CreateBuildTypeFunc(projectID, req)
}

// CreateBuildTypeCalls gets all the calls that were made to CreateBuildType.
// Check the length with:
//
//	len(mockedClientInterface.CreateBuildTypeCalls())
func (mock *ClientInterfaceMock) CreateBuildTypeCalls() []struct {
	ProjectID string
	Req       api.CreateBuildTypeRequest
} {
	var calls []struct {
		ProjectID string
		Req       api.CreateBuildTypeRequest
	}
	mock.lockCreateBuildType.RLock()
	calls = mock.calls.CreateBuildType
	mock.lockCreateBuildType.RUnlock()
	return calls
}

// CreateProject calls CreateProjectFunc.
func (mock *ClientInterfaceMock) CreateProject(req api.CreateProjectRequest) (*api.Project, error) {
	if mock.CreateProjectFunc == nil {
		panic("ClientInterfaceMock.CreateProjectFunc: method is nil but ClientInterface.CreateProject was just called")
	}
	callInfo := struct {
		Req api.CreateProjectRequest
	}{
		Req: req,
	}
	mock.lockCreateProject.Lock()
	mock.calls.CreateProject = append(mock.calls.CreateProject, callInfo)
	mock.lockCreateProject.Unlock()
	return mock.CreateProjectFunc(req)
}

// CreateProjectCalls gets all the calls that were made to CreateProject.
// Check the length with:
//
//	len(mockedClientInterface.CreateProjectCalls())
func (mock *ClientInterfaceMock) CreateProjectCalls() []struct {
	Req api.CreateProjectRequest
} {
	var calls []struct {
		Req api.CreateProjectRequest
	}
	mock.lockCreateProject.RLock()
	calls = mock.calls.CreateProject
	mock.lockCreateProject.RUnlock()
	return calls
}

// CreateSecureToken calls CreateSecureTokenFunc.
func (mock *ClientInterfaceMock) CreateSecureToken(projectID string, value string) (string, error) {
	if mock.CreateSecureTokenFunc == nil {
		panic("ClientInterfaceMock.CreateSecureTokenFunc: method is nil but ClientInterface.CreateSecureToken was just called")
	}
	callInfo := struct {
		ProjectID string
		Value     string
	}{
		ProjectID: projectID,
		Value:     value,
	}
	mock.lockCreateSecureToken.Lock()
	mock.calls.CreateSecureToken = append(mock.calls.CreateSecureToken, callInfo)
	mock.lockCreateSecureToken.Unlock()
	return mock.CreateSecureTokenFunc(projectID, value)
}

// CreateSecureTokenCalls gets all the calls that were made to CreateSecureToken.
// Check the length with:
//
//	len(mockedClientInterface.CreateSecureTokenCalls())
func (mock *ClientInterfaceMock) CreateSecureTokenCalls() []struct {
	ProjectID string
	Value     string
} {
	var calls []struct {
		ProjectID string
		Value     string
	}
	mock.lockCreateSecureToken.RLock()
	calls = mock.calls.CreateSecureToken
	mock.lockCreateSecureToken.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *ClientInterfaceMock) CreateUser(req api.CreateUserRequest) (*api.User, error) {
	if mock.CreateUserFunc == nil {
		panic("ClientInterfaceMock.CreateUserFunc: method is nil but ClientInterface.CreateUser was just called")
	}
	callInfo := struct {
		Req api.CreateUserRequest
	}{
		Req: req,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(req)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedClientInterface.CreateUserCalls())
func (mock *ClientInterfaceMock) CreateUserCalls() []struct {
	Req api.CreateUserRequest
} {
	var calls []struct {
		Req api.CreateUserRequest
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// DeleteAPIToken calls DeleteAPITokenFunc.
func (mock *ClientInterfaceMock) DeleteAPIToken(name string) error {
	if mock.DeleteAPITokenFunc == nil {
		panic("ClientInterfaceMock.DeleteAPITokenFunc: method is nil but ClientInterface.DeleteAPIToken was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockDeleteAPIToken.Lock()
	mock.calls.DeleteAPIToken = append(mock.calls.DeleteAPIToken, callInfo)
	mock.lockDeleteAPIToken.Unlock()
	return mock.DeleteAPITokenFunc(name)
}

// DeleteAPITokenCalls gets all the calls that were made to DeleteAPIToken.
// Check the length with:
//
//	len(mockedClientInterface.DeleteAPITokenCalls())
func (mock *ClientInterfaceMock) DeleteAPITokenCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockDeleteAPIToken.RLock()
	calls = mock.calls.DeleteAPIToken
	mock.lockDeleteAPIToken.RUnlock()
	return calls
}

// DeleteBuildComment calls DeleteBuildCommentFunc.
func (mock *ClientInterfaceMock) DeleteBuildComment(buildID string) error {
	if mock.DeleteBuildCommentFunc == nil {
		panic("ClientInterfaceMock.DeleteBuildCommentFunc: method is nil but ClientInterface.DeleteBuildComment was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockDeleteBuildComment.Lock()
	mock.calls.DeleteBuildComment = append(mock.calls.DeleteBuildComment, callInfo)
	mock.lockDeleteBuildComment.Unlock()
	return mock.DeleteBuildCommentFunc(buildID)
}

// DeleteBuildCommentCalls gets all the calls that were made to DeleteBuildComment.
// Check the length with:
//
//	len(mockedClientInterface.DeleteBuildCommentCalls())
func (mock *ClientInterfaceMock) DeleteBuildCommentCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockDeleteBuildComment.RLock()
	calls = mock.calls.DeleteBuildComment
	mock.lockDeleteBuildComment.RUnlock()
	return calls
}

// DeleteBuildTypeParameter calls DeleteBuildTypeParameterFunc.
func (mock *ClientInterfaceMock) DeleteBuildTypeParameter(buildTypeID string, name string) error {
	if mock.DeleteBuildTypeParameterFunc == nil {
		panic("ClientInterfaceMock.DeleteBuildTypeParameterFunc: method is nil but ClientInterface.DeleteBuildTypeParameter was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Name        string
	}{
		BuildTypeID: buildTypeID,
		Name:        name,
	}
	mock.lockDeleteBuildTypeParameter.Lock()
	mock.calls.DeleteBuildTypeParameter = append(mock.calls.DeleteBuildTypeParameter, callInfo)
	mock.lockDeleteBuildTypeParameter.Unlock()
	return mock.DeleteBuildTypeParameterFunc(buildTypeID, name)
}

// DeleteBuildTypeParameterCalls gets all the calls that were made to DeleteBuildTypeParameter.
// Check the length with:
//
//	len(mockedClientInterface.DeleteBuildTypeParameterCalls())
func (mock *ClientInterfaceMock) DeleteBuildTypeParameterCalls() []struct {
	BuildTypeID string
	Name        string
} {
	var calls []struct {
		BuildTypeID string
		Name        string
	}
	mock.lockDeleteBuildTypeParameter.RLock()
	calls = mock.calls.DeleteBuildTypeParameter
	mock.lockDeleteBuildTypeParameter.RUnlock()
	return calls
}

// DeleteProjectParameter calls DeleteProjectParameterFunc.
func (mock *ClientInterfaceMock) DeleteProjectParameter(projectID string, name string) error {
	if mock.DeleteProjectParameterFunc == nil {
		panic("ClientInterfaceMock.DeleteProjectParameterFunc: method is nil but ClientInterface.DeleteProjectParameter was just called")
	}
	callInfo := struct {
		ProjectID string
		Name      string
	}{
		ProjectID: projectID,
		Name:      name,
	}
	mock.lockDeleteProjectParameter.Lock()
	mock.calls.DeleteProjectParameter = append(mock.calls.DeleteProjectParameter, callInfo)
	mock.lockDeleteProjectParameter.Unlock()
	return mock.DeleteProjectParameterFunc(projectID, name)
}

// DeleteProjectParameterCalls gets all the calls that were made to DeleteProjectParameter.
// Check the length with:
//
//	len(mockedClientInterface.DeleteProjectParameterCalls())
func (mock *ClientInterfaceMock) DeleteProjectParameterCalls() []struct {
	ProjectID string
	Name      string
} {
	var calls []struct {
		ProjectID string
		Name      string
	}
	mock.lockDeleteProjectParameter.RLock()
	calls = mock.calls.DeleteProjectParameter
	mock.lockDeleteProjectParameter.RUnlock()
	return calls
}

// DownloadArtifact calls DownloadArtifactFunc.
func (mock *ClientInterfaceMock) DownloadArtifact(buildID string, artifactPath string) ([]byte, error) {
	if mock.DownloadArtifactFunc == nil {
		panic("ClientInterfaceMock.DownloadArtifactFunc: method is nil but ClientInterface.DownloadArtifact was just called")
	}
	callInfo := struct {
		BuildID      string
		ArtifactPath string
	}{
		BuildID:      buildID,
		ArtifactPath: artifactPath,
	}
	mock.lockDownloadArtifact.Lock()
	mock.calls.DownloadArtifact = append(mock.calls.DownloadArtifact, callInfo)
	mock.lockDownloadArtifact.Unlock()
	return mock.DownloadArtifactFunc(buildID, artifactPath)
}

// DownloadArtifactCalls gets all the calls that were made to DownloadArtifact.
// Check the length with:
//
//	len(mockedClientInterface.DownloadArtifactCalls())
func (mock *ClientInterfaceMock) DownloadArtifactCalls() []struct {
	BuildID      string
	ArtifactPath string
} {
	var calls []struct {
		BuildID      string
		ArtifactPath string
	}
	mock.lockDownloadArtifact.RLock()
	calls = mock.calls.DownloadArtifact
	mock.lockDownloadArtifact.RUnlock()
	return calls
}

// GetAgents calls GetAgentsFunc.
func (mock *ClientInterfaceMock) GetAgents(opts api.AgentsOptions) (*api.AgentList, error) {
	if mock.GetAgentsFunc == nil {
		panic("ClientInterfaceMock.GetAgentsFunc: method is nil but ClientInterface.GetAgents was just called")
	}
	callInfo := struct {
		Opts api.AgentsOptions
	}{
		Opts: opts,
	}
	mock.lockGetAgents.Lock()
	mock.calls.GetAgents = append(mock.calls.GetAgents, callInfo)
	mock.lockGetAgents.Unlock()
	return mock.GetAgentsFunc(opts)
}

// GetAgentsCalls gets all the calls that were made to GetAgents.
// Check the length with:
//
//	len(mockedClientInterface.GetAgentsCalls())
func (mock *ClientInterfaceMock) GetAgentsCalls() []struct {
	Opts api.AgentsOptions
} {
	var calls []struct {
		Opts api.AgentsOptions
	}
	mock.lockGetAgents.RLock()
	calls = mock.calls.GetAgents
	mock.lockGetAgents.RUnlock()
	return calls
}

// GetArtifacts calls GetArtifactsFunc.
func (mock *ClientInterfaceMock) GetArtifacts(buildID string) (*api.Artifacts, error) {
	if mock.GetArtifactsFunc == nil {
		panic("ClientInterfaceMock.GetArtifactsFunc: method is nil but ClientInterface.GetArtifacts was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetArtifacts.Lock()
	mock.calls.GetArtifacts = append(mock.calls.GetArtifacts, callInfo)
	mock.lockGetArtifacts.Unlock()
	return mock.GetArtifactsFunc(buildID)
}

// GetArtifactsCalls gets all the calls that were made to GetArtifacts.
// Check the length with:
//
//	len(mockedClientInterface.GetArtifactsCalls())
func (mock *ClientInterfaceMock) GetArtifactsCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetArtifacts.RLock()
	calls = mock.calls.GetArtifacts
	mock.lockGetArtifacts.RUnlock()
	return calls
}

// GetBuild calls GetBuildFunc.
func (mock *ClientInterfaceMock) GetBuild(ref string) (*api.Build, error) {
	if mock.GetBuildFunc == nil {
		panic("ClientInterfaceMock.GetBuildFunc: method is nil but ClientInterface.GetBuild was just called")
	}
	callInfo := struct {
		Ref string
	}{
		Ref: ref,
	}
	mock.lockGetBuild.Lock()
	mock.calls.GetBuild = append(mock.calls.GetBuild, callInfo)
	mock.lockGetBuild.Unlock()
	return mock.GetBuildFunc(ref)
}

// GetBuildCalls gets all the calls that were made to GetBuild.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildCalls())
func (mock *ClientInterfaceMock) GetBuildCalls() []struct {
	Ref string
} {
	var calls []struct {
		Ref string
	}
	mock.lockGetBuild.RLock()
	calls = mock.calls.GetBuild
	mock.lockGetBuild.RUnlock()
	return calls
}

// GetBuildChanges calls GetBuildChangesFunc.
func (mock *ClientInterfaceMock) GetBuildChanges(buildID string) (*api.ChangeList, error) {
	if mock.GetBuildChangesFunc == nil {
		panic("ClientInterfaceMock.GetBuildChangesFunc: method is nil but ClientInterface.GetBuildChanges was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetBuildChanges.Lock()
	mock.calls.GetBuildChanges = append(mock.calls.GetBuildChanges, callInfo)
	mock.lockGetBuildChanges.Unlock()
	return mock.GetBuildChangesFunc(buildID)
}

// GetBuildChangesCalls gets all the calls that were made to GetBuildChanges.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildChangesCalls())
func (mock *ClientInterfaceMock) GetBuildChangesCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetBuildChanges.RLock()
	calls = mock.calls.GetBuildChanges
	mock.lockGetBuildChanges.RUnlock()
	return calls
}

// GetBuildComment calls GetBuildCommentFunc.
func (mock *ClientInterfaceMock) GetBuildComment(buildID string) (string, error) {
	if mock.GetBuildCommentFunc == nil {
		panic("ClientInterfaceMock.GetBuildCommentFunc: method is nil but ClientInterface.GetBuildComment was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetBuildComment.Lock()
	mock.calls.GetBuildComment = append(mock.calls.GetBuildComment, callInfo)
	mock.lockGetBuildComment.Unlock()
	return mock.GetBuildCommentFunc(buildID)
}

// GetBuildCommentCalls gets all the calls that were made to GetBuildComment.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildCommentCalls())
func (mock *ClientInterfaceMock) GetBuildCommentCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetBuildComment.RLock()
	calls = mock.calls.GetBuildComment
	mock.lockGetBuildComment.RUnlock()
	return calls
}

// GetBuildLog calls GetBuildLogFunc.
func (mock *ClientInterfaceMock) GetBuildLog(buildID string) (string, error) {
	if mock.GetBuildLogFunc == nil {
		panic("ClientInterfaceMock.GetBuildLogFunc: method is nil but ClientInterface.GetBuildLog was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetBuildLog.Lock()
	mock.calls.GetBuildLog = append(mock.calls.GetBuildLog, callInfo)
	mock.lockGetBuildLog.Unlock()
	return mock.GetBuildLogFunc(buildID)
}

// GetBuildLogCalls gets all the calls that were made to GetBuildLog.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildLogCalls())
func (mock *ClientInterfaceMock) GetBuildLogCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetBuildLog.RLock()
	calls = mock.calls.GetBuildLog
	mock.lockGetBuildLog.RUnlock()
	return calls
}

// GetBuildQueue calls GetBuildQueueFunc.
func (mock *ClientInterfaceMock) GetBuildQueue(opts api.QueueOptions) (*api.BuildQueue, error) {
	if mock.GetBuildQueueFunc == nil {
		panic("ClientInterfaceMock.GetBuildQueueFunc: method is nil but ClientInterface.GetBuildQueue was just called")
	}
	callInfo := struct {
		Opts api.QueueOptions
	}{
		Opts: opts,
	}
	mock.lockGetBuildQueue.Lock()
	mock.calls.GetBuildQueue = append(mock.calls.GetBuildQueue, callInfo)
	mock.lockGetBuildQueue.Unlock()
	return mock.GetBuildQueueFunc(opts)
}

// GetBuildQueueCalls gets all the calls that were made to GetBuildQueue.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildQueueCalls())
func (mock *ClientInterfaceMock) GetBuildQueueCalls() []struct {
	Opts api.QueueOptions
} {
	var calls []struct {
		Opts api.QueueOptions
	}
	mock.lockGetBuildQueue.RLock()
	calls = mock.calls.GetBuildQueue
	mock.lockGetBuildQueue.RUnlock()
	return calls
}

// GetBuildTags calls GetBuildTagsFunc.
func (mock *ClientInterfaceMock) GetBuildTags(buildID string) (*api.TagList, error) {
	if mock.GetBuildTagsFunc == nil {
		panic("ClientInterfaceMock.GetBuildTagsFunc: method is nil but ClientInterface.GetBuildTags was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetBuildTags.Lock()
	mock.calls.GetBuildTags = append(mock.calls.GetBuildTags, callInfo)
	mock.lockGetBuildTags.Unlock()
	return mock.GetBuildTagsFunc(buildID)
}

// GetBuildTagsCalls gets all the calls that were made to GetBuildTags.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTagsCalls())
func (mock *ClientInterfaceMock) GetBuildTagsCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetBuildTags.RLock()
	calls = mock.calls.GetBuildTags
	mock.lockGetBuildTags.RUnlock()
	return calls
}

// GetBuildTests calls GetBuildTestsFunc.
func (mock *ClientInterfaceMock) GetBuildTests(buildID string, failedOnly bool, limit int) (*api.TestOccurrences, error) {
	if mock.GetBuildTestsFunc == nil {
		panic("ClientInterfaceMock.GetBuildTestsFunc: method is nil but ClientInterface.GetBuildTests was just called")
	}
	callInfo := struct {
		BuildID    string
		FailedOnly bool
		Limit      int
	}{
		BuildID:    buildID,
		FailedOnly: failedOnly,
		Limit:      limit,
	}
	mock.lockGetBuildTests.Lock()
	mock.calls.GetBuildTests = append(mock.calls.GetBuildTests, callInfo)
	mock.lockGetBuildTests.Unlock()
	return mock.GetBuildTestsFunc(buildID, failedOnly, limit)
}

// GetBuildTestsCalls gets all the calls that were made to GetBuildTests.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTestsCalls())
func (mock *ClientInterfaceMock) GetBuildTestsCalls() []struct {
	BuildID    string
	FailedOnly bool
	Limit      int
} {
	var calls []struct {
		BuildID    string
		FailedOnly bool
		Limit      int
	}
	mock.lockGetBuildTests.RLock()
	calls = mock.calls.GetBuildTests
	mock.lockGetBuildTests.RUnlock()
	return calls
}

// GetBuildType calls GetBuildTypeFunc.
func (mock *ClientInterfaceMock) GetBuildType(id string) (*api.BuildType, error) {
	if mock.GetBuildTypeFunc == nil {
		panic("ClientInterfaceMock.GetBuildTypeFunc: method is nil but ClientInterface.GetBuildType was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetBuildType.Lock()
	mock.calls.GetBuildType = append(mock.calls.GetBuildType, callInfo)
	mock.lockGetBuildType.Unlock()
	return mock.GetBuildTypeFunc(id)
}

// GetBuildTypeCalls gets all the calls that were made to GetBuildType.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTypeCalls())
func (mock *ClientInterfaceMock) GetBuildTypeCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetBuildType.RLock()
	calls = mock.calls.GetBuildType
	mock.lockGetBuildType.RUnlock()
	return calls
}

// GetBuildTypeParameter calls GetBuildTypeParameterFunc.
func (mock *ClientInterfaceMock) GetBuildTypeParameter(buildTypeID string, name string) (*api.Parameter, error) {
	if mock.GetBuildTypeParameterFunc == nil {
		panic("ClientInterfaceMock.GetBuildTypeParameterFunc: method is nil but ClientInterface.GetBuildTypeParameter was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Name        string
	}{
		BuildTypeID: buildTypeID,
		Name:        name,
	}
	mock.lockGetBuildTypeParameter.Lock()
	mock.calls.GetBuildTypeParameter = append(mock.calls.GetBuildTypeParameter, callInfo)
	mock.lockGetBuildTypeParameter.Unlock()
	return mock.GetBuildTypeParameterFunc(buildTypeID, name)
}

// GetBuildTypeParameterCalls gets all the calls that were made to GetBuildTypeParameter.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTypeParameterCalls())
func (mock *ClientInterfaceMock) GetBuildTypeParameterCalls() []struct {
	BuildTypeID string
	Name        string
} {
	var calls []struct {
		BuildTypeID string
		Name        string
	}
	mock.lockGetBuildTypeParameter.RLock()
	calls = mock.calls.GetBuildTypeParameter
	mock.lockGetBuildTypeParameter.RUnlock()
	return calls
}

// GetBuildTypeParameters calls GetBuildTypeParametersFunc.
func (mock *ClientInterfaceMock) GetBuildTypeParameters(buildTypeID string) (*api.ParameterList, error) {
	if mock.GetBuildTypeParametersFunc == nil {
		panic("ClientInterfaceMock.GetBuildTypeParametersFunc: method is nil but ClientInterface.GetBuildTypeParameters was just called")
	}
	callInfo := struct {
		BuildTypeID string
	}{
		BuildTypeID: buildTypeID,
	}
	mock.lockGetBuildTypeParameters.Lock()
	mock.calls.GetBuildTypeParameters = append(mock.calls.GetBuildTypeParameters, callInfo)
	mock.lockGetBuildTypeParameters.Unlock()
	return mock.GetBuildTypeParametersFunc(buildTypeID)
}

// GetBuildTypeParametersCalls gets all the calls that were made to GetBuildTypeParameters.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTypeParametersCalls())
func (mock *ClientInterfaceMock) GetBuildTypeParametersCalls() []struct {
	BuildTypeID string
} {
	var calls []struct {
		BuildTypeID string
	}
	mock.lockGetBuildTypeParameters.RLock()
	calls = mock.calls.GetBuildTypeParameters
	mock.lockGetBuildTypeParameters.RUnlock()
	return calls
}

// GetBuildTypes calls GetBuildTypesFunc.
func (mock *ClientInterfaceMock) GetBuildTypes(opts api.BuildTypesOptions) (*api.BuildTypeList, error) {
	if mock.GetBuildTypesFunc == nil {
		panic("ClientInterfaceMock.GetBuildTypesFunc: method is nil but ClientInterface.GetBuildTypes was just called")
	}
	callInfo := struct {
		Opts api.BuildTypesOptions
	}{
		Opts: opts,
	}
	mock.lockGetBuildTypes.Lock()
	mock.calls.GetBuildTypes = append(mock.calls.GetBuildTypes, callInfo)
	mock.lockGetBuildTypes.Unlock()
	return mock.GetBuildTypesFunc(opts)
}

// GetBuildTypesCalls gets all the calls that were made to GetBuildTypes.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildTypesCalls())
func (mock *ClientInterfaceMock) GetBuildTypesCalls() []struct {
	Opts api.BuildTypesOptions
} {
	var calls []struct {
		Opts api.BuildTypesOptions
	}
	mock.lockGetBuildTypes.RLock()
	calls = mock.calls.GetBuildTypes
	mock.lockGetBuildTypes.RUnlock()
	return calls
}

// GetBuilds calls GetBuildsFunc.
func (mock *ClientInterfaceMock) GetBuilds(opts api.BuildsOptions) (*api.BuildList, error) {
	if mock.GetBuildsFunc == nil {
		panic("ClientInterfaceMock.GetBuildsFunc: method is nil but ClientInterface.GetBuilds was just called")
	}
	callInfo := struct {
		Opts api.BuildsOptions
	}{
		Opts: opts,
	}
	mock.lockGetBuilds.Lock()
	mock.calls.GetBuilds = append(mock.calls.GetBuilds, callInfo)
	mock.lockGetBuilds.Unlock()
	return mock.GetBuildsFunc(opts)
}

// GetBuildsCalls gets all the calls that were made to GetBuilds.
// Check the length with:
//
//	len(mockedClientInterface.GetBuildsCalls())
func (mock *ClientInterfaceMock) GetBuildsCalls() []struct {
	Opts api.BuildsOptions
} {
	var calls []struct {
		Opts api.BuildsOptions
	}
	mock.lockGetBuilds.RLock()
	calls = mock.calls.GetBuilds
	mock.lockGetBuilds.RUnlock()
	return calls
}

// GetCurrentUser calls GetCurrentUserFunc.
func (mock *ClientInterfaceMock) GetCurrentUser() (*api.User, error) {
	if mock.GetCurrentUserFunc == nil {
		panic("ClientInterfaceMock.GetCurrentUserFunc: method is nil but ClientInterface.GetCurrentUser was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCurrentUser.Lock()
	mock.calls.GetCurrentUser = append(mock.calls.GetCurrentUser, callInfo)
	mock.lockGetCurrentUser.Unlock()
	return mock.GetCurrentUserFunc()
}

// GetCurrentUserCalls gets all the calls that were made to GetCurrentUser.
// Check the length with:
//
//	len(mockedClientInterface.GetCurrentUserCalls())
func (mock *ClientInterfaceMock) GetCurrentUserCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCurrentUser.RLock()
	calls = mock.calls.GetCurrentUser
	mock.lockGetCurrentUser.RUnlock()
	return calls
}

// GetParameterValue calls GetParameterValueFunc.
func (mock *ClientInterfaceMock) GetParameterValue(path string) (string, error) {
	if mock.GetParameterValueFunc == nil {
		panic("ClientInterfaceMock.GetParameterValueFunc: method is nil but ClientInterface.GetParameterValue was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockGetParameterValue.Lock()
	mock.calls.GetParameterValue = append(mock.calls.GetParameterValue, callInfo)
	mock.lockGetParameterValue.Unlock()
	return mock.GetParameterValueFunc(path)
}

// GetParameterValueCalls gets all the calls that were made to GetParameterValue.
// Check the length with:
//
//	len(mockedClientInterface.GetParameterValueCalls())
func (mock *ClientInterfaceMock) GetParameterValueCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockGetParameterValue.RLock()
	calls = mock.calls.GetParameterValue
	mock.lockGetParameterValue.RUnlock()
	return calls
}

// GetProject calls GetProjectFunc.
func (mock *ClientInterfaceMock) GetProject(id string) (*api.Project, error) {
	if mock.GetProjectFunc == nil {
		panic("ClientInterfaceMock.GetProjectFunc: method is nil but ClientInterface.GetProject was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetProject.Lock()
	mock.calls.GetProject = append(mock.calls.GetProject, callInfo)
	mock.lockGetProject.Unlock()
	return mock.GetProjectFunc(id)
}

// GetProjectCalls gets all the calls that were made to GetProject.
// Check the length with:
//
//	len(mockedClientInterface.GetProjectCalls())
func (mock *ClientInterfaceMock) GetProjectCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetProject.RLock()
	calls = mock.calls.GetProject
	mock.lockGetProject.RUnlock()
	return calls
}

// GetProjectParameter calls GetProjectParameterFunc.
func (mock *ClientInterfaceMock) GetProjectParameter(projectID string, name string) (*api.Parameter, error) {
	if mock.GetProjectParameterFunc == nil {
		panic("ClientInterfaceMock.GetProjectParameterFunc: method is nil but ClientInterface.GetProjectParameter was just called")
	}
	callInfo := struct {
		ProjectID string
		Name      string
	}{
		ProjectID: projectID,
		Name:      name,
	}
	mock.lockGetProjectParameter.Lock()
	mock.calls.GetProjectParameter = append(mock.calls.GetProjectParameter, callInfo)
	mock.lockGetProjectParameter.Unlock()
	return mock.GetProjectParameterFunc(projectID, name)
}

// GetProjectParameterCalls gets all the calls that were made to GetProjectParameter.
// Check the length with:
//
//	len(mockedClientInterface.GetProjectParameterCalls())
func (mock *ClientInterfaceMock) GetProjectParameterCalls() []struct {
	ProjectID string
	Name      string
} {
	var calls []struct {
		ProjectID string
		Name      string
	}
	mock.lockGetProjectParameter.RLock()
	calls = mock.calls.GetProjectParameter
	mock.lockGetProjectParameter.RUnlock()
	return calls
}

// GetProjectParameters calls GetProjectParametersFunc.
func (mock *ClientInterfaceMock) GetProjectParameters(projectID string) (*api.ParameterList, error) {
	if mock.GetProjectParametersFunc == nil {
		panic("ClientInterfaceMock.GetProjectParametersFunc: method is nil but ClientInterface.GetProjectParameters was just called")
	}
	callInfo := struct {
		ProjectID string
	}{
		ProjectID: projectID,
	}
	mock.lockGetProjectParameters.Lock()
	mock.calls.GetProjectParameters = append(mock.calls.GetProjectParameters, callInfo)
	mock.lockGetProjectParameters.Unlock()
	return mock.GetProjectParametersFunc(projectID)
}

// GetProjectParametersCalls gets all the calls that were made to GetProjectParameters.
// Check the length with:
//
//	len(mockedClientInterface.GetProjectParametersCalls())
func (mock *ClientInterfaceMock) GetProjectParametersCalls() []struct {
	ProjectID string
} {
	var calls []struct {
		ProjectID string
	}
	mock.lockGetProjectParameters.RLock()
	calls = mock.calls.GetProjectParameters
	mock.lockGetProjectParameters.RUnlock()
	return calls
}

// GetProjects calls GetProjectsFunc.
func (mock *ClientInterfaceMock) GetProjects(opts api.ProjectsOptions) (*api.ProjectList, error) {
	if mock.GetProjectsFunc == nil {
		panic("ClientInterfaceMock.GetProjectsFunc: method is nil but ClientInterface.GetProjects was just called")
	}
	callInfo := struct {
		Opts api.ProjectsOptions
	}{
		Opts: opts,
	}
	mock.lockGetProjects.Lock()
	mock.calls.GetProjects = append(mock.calls.GetProjects, callInfo)
	mock.lockGetProjects.Unlock()
	return mock.GetProjectsFunc(opts)
}

// GetProjectsCalls gets all the calls that were made to GetProjects.
// Check the length with:
//
//	len(mockedClientInterface.GetProjectsCalls())
func (mock *ClientInterfaceMock) GetProjectsCalls() []struct {
	Opts api.ProjectsOptions
} {
	var calls []struct {
		Opts api.ProjectsOptions
	}
	mock.lockGetProjects.RLock()
	calls = mock.calls.GetProjects
	mock.lockGetProjects.RUnlock()
	return calls
}

// GetQueuedBuildApprovalInfo calls GetQueuedBuildApprovalInfoFunc.
func (mock *ClientInterfaceMock) GetQueuedBuildApprovalInfo(buildID string) (*api.ApprovalInfo, error) {
	if mock.GetQueuedBuildApprovalInfoFunc == nil {
		panic("ClientInterfaceMock.GetQueuedBuildApprovalInfoFunc: method is nil but ClientInterface.GetQueuedBuildApprovalInfo was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockGetQueuedBuildApprovalInfo.Lock()
	mock.calls.GetQueuedBuildApprovalInfo = append(mock.calls.GetQueuedBuildApprovalInfo, callInfo)
	mock.lockGetQueuedBuildApprovalInfo.Unlock()
	return mock.GetQueuedBuildApprovalInfoFunc(buildID)
}

// GetQueuedBuildApprovalInfoCalls gets all the calls that were made to GetQueuedBuildApprovalInfo.
// Check the length with:
//
//	len(mockedClientInterface.GetQueuedBuildApprovalInfoCalls())
func (mock *ClientInterfaceMock) GetQueuedBuildApprovalInfoCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockGetQueuedBuildApprovalInfo.RLock()
	calls = mock.calls.GetQueuedBuildApprovalInfo
	mock.lockGetQueuedBuildApprovalInfo.RUnlock()
	return calls
}

// GetSecureValue calls GetSecureValueFunc.
func (mock *ClientInterfaceMock) GetSecureValue(projectID string, token string) (string, error) {
	if mock.GetSecureValueFunc == nil {
		panic("ClientInterfaceMock.GetSecureValueFunc: method is nil but ClientInterface.GetSecureValue was just called")
	}
	callInfo := struct {
		ProjectID string
		Token     string
	}{
		ProjectID: projectID,
		Token:     token,
	}
	mock.lockGetSecureValue.Lock()
	mock.calls.GetSecureValue = append(mock.calls.GetSecureValue, callInfo)
	mock.lockGetSecureValue.Unlock()
	return mock.GetSecureValueFunc(projectID, token)
}

// GetSecureValueCalls gets all the calls that were made to GetSecureValue.
// Check the length with:
//
//	len(mockedClientInterface.GetSecureValueCalls())
func (mock *ClientInterfaceMock) GetSecureValueCalls() []struct {
	ProjectID string
	Token     string
} {
	var calls []struct {
		ProjectID string
		Token     string
	}
	mock.lockGetSecureValue.RLock()
	calls = mock.calls.GetSecureValue
	mock.lockGetSecureValue.RUnlock()
	return calls
}

// GetServer calls GetServerFunc.
func (mock *ClientInterfaceMock) GetServer() (*api.Server, error) {
	if mock.GetServerFunc == nil {
		panic("ClientInterfaceMock.GetServerFunc: method is nil but ClientInterface.GetServer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetServer.Lock()
	mock.calls.GetServer = append(mock.calls.GetServer, callInfo)
	mock.lockGetServer.Unlock()
	return mock.GetServerFunc()
}

// GetServerCalls gets all the calls that were made to GetServer.
// Check the length with:
//
//	len(mockedClientInterface.GetServerCalls())
func (mock *ClientInterfaceMock) GetServerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetServer.RLock()
	calls = mock.calls.GetServer
	mock.lockGetServer.RUnlock()
	return calls
}

// GetUser calls GetUserFunc.
func (mock *ClientInterfaceMock) GetUser(username string) (*api.User, error) {
	if mock.GetUserFunc == nil {
		panic("ClientInterfaceMock.GetUserFunc: method is nil but ClientInterface.GetUser was just called")
	}
	callInfo := struct {
		Username string
	}{
		Username: username,
	}
	mock.lockGetUser.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	mock.lockGetUser.Unlock()
	return mock.GetUserFunc(username)
}

// GetUserCalls gets all the calls that were made to GetUser.
// Check the length with:
//
//	len(mockedClientInterface.GetUserCalls())
func (mock *ClientInterfaceMock) GetUserCalls() []struct {
	Username string
} {
	var calls []struct {
		Username string
	}
	mock.lockGetUser.RLock()
	calls = mock.calls.GetUser
	mock.lockGetUser.RUnlock()
	return calls
}

// MoveQueuedBuildToTop calls MoveQueuedBuildToTopFunc.
func (mock *ClientInterfaceMock) MoveQueuedBuildToTop(buildID string) error {
	if mock.MoveQueuedBuildToTopFunc == nil {
		panic("ClientInterfaceMock.MoveQueuedBuildToTopFunc: method is nil but ClientInterface.MoveQueuedBuildToTop was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockMoveQueuedBuildToTop.Lock()
	mock.calls.MoveQueuedBuildToTop = append(mock.calls.MoveQueuedBuildToTop, callInfo)
	mock.lockMoveQueuedBuildToTop.Unlock()
	return mock.MoveQueuedBuildToTopFunc(buildID)
}

// MoveQueuedBuildToTopCalls gets all the calls that were made to MoveQueuedBuildToTop.
// Check the length with:
//
//	len(mockedClientInterface.MoveQueuedBuildToTopCalls())
func (mock *ClientInterfaceMock) MoveQueuedBuildToTopCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockMoveQueuedBuildToTop.RLock()
	calls = mock.calls.MoveQueuedBuildToTop
	mock.lockMoveQueuedBuildToTop.RUnlock()
	return calls
}

// PinBuild calls PinBuildFunc.
func (mock *ClientInterfaceMock) PinBuild(buildID string, comment string) error {
	if mock.PinBuildFunc == nil {
		panic("ClientInterfaceMock.PinBuildFunc: method is nil but ClientInterface.PinBuild was just called")
	}
	callInfo := struct {
		BuildID string
		Comment string
	}{
		BuildID: buildID,
		Comment: comment,
	}
	mock.lockPinBuild.Lock()
	mock.calls.PinBuild = append(mock.calls.PinBuild, callInfo)
	mock.lockPinBuild.Unlock()
	return mock.PinBuildFunc(buildID, comment)
}

// PinBuildCalls gets all the calls that were made to PinBuild.
// Check the length with:
//
//	len(mockedClientInterface.PinBuildCalls())
func (mock *ClientInterfaceMock) PinBuildCalls() []struct {
	BuildID string
	Comment string
} {
	var calls []struct {
		BuildID string
		Comment string
	}
	mock.lockPinBuild.RLock()
	calls = mock.calls.PinBuild
	mock.lockPinBuild.RUnlock()
	return calls
}

// ProjectExists calls ProjectExistsFunc.
func (mock *ClientInterfaceMock) ProjectExists(id string) bool {
	if mock.ProjectExistsFunc == nil {
		panic("ClientInterfaceMock.ProjectExistsFunc: method is nil but ClientInterface.ProjectExists was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockProjectExists.Lock()
	mock.calls.ProjectExists = append(mock.calls.ProjectExists, callInfo)
	mock.lockProjectExists.Unlock()
	return mock.ProjectExistsFunc(id)
}

// ProjectExistsCalls gets all the calls that were made to ProjectExists.
// Check the length with:
//
//	len(mockedClientInterface.ProjectExistsCalls())
func (mock *ClientInterfaceMock) ProjectExistsCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockProjectExists.RLock()
	calls = mock.calls.ProjectExists
	mock.lockProjectExists.RUnlock()
	return calls
}

// RawRequest calls RawRequestFunc.
func (mock *ClientInterfaceMock) RawRequest(method string, path string, body io.Reader, headers map[string]string) (*api.RawResponse, error) {
	if mock.RawRequestFunc == nil {
		panic("ClientInterfaceMock.RawRequestFunc: method is nil but ClientInterface.RawRequest was just called")
	}
	callInfo := struct {
		Method  string
		Path    string
		Body    io.Reader
		Headers map[string]string
	}{
		Method:  method,
		Path:    path,
		Body:    body,
		Headers: headers,
	}
	mock.lockRawRequest.Lock()
	mock.calls.RawRequest = append(mock.calls.RawRequest, callInfo)
	mock.lockRawRequest.Unlock()
	return mock.RawRequestFunc(method, path, body, headers)
}

// RawRequestCalls gets all the calls that were made to RawRequest.
// Check the length with:
//
//	len(mockedClientInterface.RawRequestCalls())
func (mock *ClientInterfaceMock) RawRequestCalls() []struct {
	Method  string
	Path    string
	Body    io.Reader
	Headers map[string]string
} {
	var calls []struct {
		Method  string
		Path    string
		Body    io.Reader
		Headers map[string]string
	}
	mock.lockRawRequest.RLock()
	calls = mock.calls.RawRequest
	mock.lockRawRequest.RUnlock()
	return calls
}

// RemoveBuildTag calls RemoveBuildTagFunc.
func (mock *ClientInterfaceMock) RemoveBuildTag(buildID string, tag string) error {
	if mock.RemoveBuildTagFunc == nil {
		panic("ClientInterfaceMock.RemoveBuildTagFunc: method is nil but ClientInterface.RemoveBuildTag was just called")
	}
	callInfo := struct {
		BuildID string
		Tag     string
	}{
		BuildID: buildID,
		Tag:     tag,
	}
	mock.lockRemoveBuildTag.Lock()
	mock.calls.RemoveBuildTag = append(mock.calls.RemoveBuildTag, callInfo)
	mock.lockRemoveBuildTag.Unlock()
	return mock.RemoveBuildTagFunc(buildID, tag)
}

// RemoveBuildTagCalls gets all the calls that were made to RemoveBuildTag.
// Check the length with:
//
//	len(mockedClientInterface.RemoveBuildTagCalls())
func (mock *ClientInterfaceMock) RemoveBuildTagCalls() []struct {
	BuildID string
	Tag     string
} {
	var calls []struct {
		BuildID string
		Tag     string
	}
	mock.lockRemoveBuildTag.RLock()
	calls = mock.calls.RemoveBuildTag
	mock.lockRemoveBuildTag.RUnlock()
	return calls
}

// RemoveFromQueue calls RemoveFromQueueFunc.
func (mock *ClientInterfaceMock) RemoveFromQueue(id string) error {
	if mock.RemoveFromQueueFunc == nil {
		panic("ClientInterfaceMock.RemoveFromQueueFunc: method is nil but ClientInterface.RemoveFromQueue was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockRemoveFromQueue.Lock()
	mock.calls.RemoveFromQueue = append(mock.calls.RemoveFromQueue, callInfo)
	mock.lockRemoveFromQueue.Unlock()
	return mock.RemoveFromQueueFunc(id)
}

// RemoveFromQueueCalls gets all the calls that were made to RemoveFromQueue.
// Check the length with:
//
//	len(mockedClientInterface.RemoveFromQueueCalls())
func (mock *ClientInterfaceMock) RemoveFromQueueCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockRemoveFromQueue.RLock()
	calls = mock.calls.RemoveFromQueue
	mock.lockRemoveFromQueue.RUnlock()
	return calls
}

// ResolveBuildID calls ResolveBuildIDFunc.
func (mock *ClientInterfaceMock) ResolveBuildID(ref string) (string, error) {
	if mock.ResolveBuildIDFunc == nil {
		panic("ClientInterfaceMock.ResolveBuildIDFunc: method is nil but ClientInterface.ResolveBuildID was just called")
	}
	callInfo := struct {
		Ref string
	}{
		Ref: ref,
	}
	mock.lockResolveBuildID.Lock()
	mock.calls.ResolveBuildID = append(mock.calls.ResolveBuildID, callInfo)
	mock.lockResolveBuildID.Unlock()
	return mock.ResolveBuildIDFunc(ref)
}

// ResolveBuildIDCalls gets all the calls that were made to ResolveBuildID.
// Check the length with:
//
//	len(mockedClientInterface.ResolveBuildIDCalls())
func (mock *ClientInterfaceMock) ResolveBuildIDCalls() []struct {
	Ref string
} {
	var calls []struct {
		Ref string
	}
	mock.lockResolveBuildID.RLock()
	calls = mock.calls.ResolveBuildID
	mock.lockResolveBuildID.RUnlock()
	return calls
}

// RunBuild calls RunBuildFunc.
func (mock *ClientInterfaceMock) RunBuild(buildTypeID string, opts api.RunBuildOptions) (*api.Build, error) {
	if mock.RunBuildFunc == nil {
		panic("ClientInterfaceMock.RunBuildFunc: method is nil but ClientInterface.RunBuild was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Opts        api.RunBuildOptions
	}{
		BuildTypeID: buildTypeID,
		Opts:        opts,
	}
	mock.lockRunBuild.Lock()
	mock.calls.RunBuild = append(mock.calls.RunBuild, callInfo)
	mock.lockRunBuild.Unlock()
	return mock.RunBuildFunc(buildTypeID, opts)
}

// RunBuildCalls gets all the calls that were made to RunBuild.
// Check the length with:
//
//	len(mockedClientInterface.RunBuildCalls())
func (mock *ClientInterfaceMock) RunBuildCalls() []struct {
	BuildTypeID string
	Opts        api.RunBuildOptions
} {
	var calls []struct {
		BuildTypeID string
		Opts        api.RunBuildOptions
	}
	mock.lockRunBuild.RLock()
	calls = mock.calls.RunBuild
	mock.lockRunBuild.RUnlock()
	return calls
}

// ServerVersion calls ServerVersionFunc.
func (mock *ClientInterfaceMock) ServerVersion() (*api.Server, error) {
	if mock.ServerVersionFunc == nil {
		panic("ClientInterfaceMock.ServerVersionFunc: method is nil but ClientInterface.ServerVersion was just called")
	}
	callInfo := struct {
	}{}
	mock.lockServerVersion.Lock()
	mock.calls.ServerVersion = append(mock.calls.ServerVersion, callInfo)
	mock.lockServerVersion.Unlock()
	return mock.ServerVersionFunc()
}

// ServerVersionCalls gets all the calls that were made to ServerVersion.
// Check the length with:
//
//	len(mockedClientInterface.ServerVersionCalls())
func (mock *ClientInterfaceMock) ServerVersionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockServerVersion.RLock()
	calls = mock.calls.ServerVersion
	mock.lockServerVersion.RUnlock()
	return calls
}

// SetBuildComment calls SetBuildCommentFunc.
func (mock *ClientInterfaceMock) SetBuildComment(buildID string, comment string) error {
	if mock.SetBuildCommentFunc == nil {
		panic("ClientInterfaceMock.SetBuildCommentFunc: method is nil but ClientInterface.SetBuildComment was just called")
	}
	callInfo := struct {
		BuildID string
		Comment string
	}{
		BuildID: buildID,
		Comment: comment,
	}
	mock.lockSetBuildComment.Lock()
	mock.calls.SetBuildComment = append(mock.calls.SetBuildComment, callInfo)
	mock.lockSetBuildComment.Unlock()
	return mock.SetBuildCommentFunc(buildID, comment)
}

// SetBuildCommentCalls gets all the calls that were made to SetBuildComment.
// Check the length with:
//
//	len(mockedClientInterface.SetBuildCommentCalls())
func (mock *ClientInterfaceMock) SetBuildCommentCalls() []struct {
	BuildID string
	Comment string
} {
	var calls []struct {
		BuildID string
		Comment string
	}
	mock.lockSetBuildComment.RLock()
	calls = mock.calls.SetBuildComment
	mock.lockSetBuildComment.RUnlock()
	return calls
}

// SetBuildTypeParameter calls SetBuildTypeParameterFunc.
func (mock *ClientInterfaceMock) SetBuildTypeParameter(buildTypeID string, name string, value string, secure bool) error {
	if mock.SetBuildTypeParameterFunc == nil {
		panic("ClientInterfaceMock.SetBuildTypeParameterFunc: method is nil but ClientInterface.SetBuildTypeParameter was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Name        string
		Value       string
		Secure      bool
	}{
		BuildTypeID: buildTypeID,
		Name:        name,
		Value:       value,
		Secure:      secure,
	}
	mock.lockSetBuildTypeParameter.Lock()
	mock.calls.SetBuildTypeParameter = append(mock.calls.SetBuildTypeParameter, callInfo)
	mock.lockSetBuildTypeParameter.Unlock()
	return mock.SetBuildTypeParameterFunc(buildTypeID, name, value, secure)
}

// SetBuildTypeParameterCalls gets all the calls that were made to SetBuildTypeParameter.
// Check the length with:
//
//	len(mockedClientInterface.SetBuildTypeParameterCalls())
func (mock *ClientInterfaceMock) SetBuildTypeParameterCalls() []struct {
	BuildTypeID string
	Name        string
	Value       string
	Secure      bool
} {
	var calls []struct {
		BuildTypeID string
		Name        string
		Value       string
		Secure      bool
	}
	mock.lockSetBuildTypeParameter.RLock()
	calls = mock.calls.SetBuildTypeParameter
	mock.lockSetBuildTypeParameter.RUnlock()
	return calls
}

// SetBuildTypePaused calls SetBuildTypePausedFunc.
func (mock *ClientInterfaceMock) SetBuildTypePaused(id string, paused bool) error {
	if mock.SetBuildTypePausedFunc == nil {
		panic("ClientInterfaceMock.SetBuildTypePausedFunc: method is nil but ClientInterface.SetBuildTypePaused was just called")
	}
	callInfo := struct {
		ID     string
		Paused bool
	}{
		ID:     id,
		Paused: paused,
	}
	mock.lockSetBuildTypePaused.Lock()
	mock.calls.SetBuildTypePaused = append(mock.calls.SetBuildTypePaused, callInfo)
	mock.lockSetBuildTypePaused.Unlock()
	return mock.SetBuildTypePausedFunc(id, paused)
}

// SetBuildTypePausedCalls gets all the calls that were made to SetBuildTypePaused.
// Check the length with:
//
//	len(mockedClientInterface.SetBuildTypePausedCalls())
func (mock *ClientInterfaceMock) SetBuildTypePausedCalls() []struct {
	ID     string
	Paused bool
} {
	var calls []struct {
		ID     string
		Paused bool
	}
	mock.lockSetBuildTypePaused.RLock()
	calls = mock.calls.SetBuildTypePaused
	mock.lockSetBuildTypePaused.RUnlock()
	return calls
}

// SetBuildTypeSetting calls SetBuildTypeSettingFunc.
func (mock *ClientInterfaceMock) SetBuildTypeSetting(buildTypeID string, setting string, value string) error {
	if mock.SetBuildTypeSettingFunc == nil {
		panic("ClientInterfaceMock.SetBuildTypeSettingFunc: method is nil but ClientInterface.SetBuildTypeSetting was just called")
	}
	callInfo := struct {
		BuildTypeID string
		Setting     string
		Value       string
	}{
		BuildTypeID: buildTypeID,
		Setting:     setting,
		Value:       value,
	}
	mock.lockSetBuildTypeSetting.Lock()
	mock.calls.SetBuildTypeSetting = append(mock.calls.SetBuildTypeSetting, callInfo)
	mock.lockSetBuildTypeSetting.Unlock()
	return mock.SetBuildTypeSettingFunc(buildTypeID, setting, value)
}

// SetBuildTypeSettingCalls gets all the calls that were made to SetBuildTypeSetting.
// Check the length with:
//
//	len(mockedClientInterface.SetBuildTypeSettingCalls())
func (mock *ClientInterfaceMock) SetBuildTypeSettingCalls() []struct {
	BuildTypeID string
	Setting     string
	Value       string
} {
	var calls []struct {
		BuildTypeID string
		Setting     string
		Value       string
	}
	mock.lockSetBuildTypeSetting.RLock()
	calls = mock.calls.SetBuildTypeSetting
	mock.lockSetBuildTypeSetting.RUnlock()
	return calls
}

// SetProjectParameter calls SetProjectParameterFunc.
func (mock *ClientInterfaceMock) SetProjectParameter(projectID string, name string, value string, secure bool) error {
	if mock.SetProjectParameterFunc == nil {
		panic("ClientInterfaceMock.SetProjectParameterFunc: method is nil but ClientInterface.SetProjectParameter was just called")
	}
	callInfo := struct {
		ProjectID string
		Name      string
		Value     string
		Secure    bool
	}{
		ProjectID: projectID,
		Name:      name,
		Value:     value,
		Secure:    secure,
	}
	mock.lockSetProjectParameter.Lock()
	mock.calls.SetProjectParameter = append(mock.calls.SetProjectParameter, callInfo)
	mock.lockSetProjectParameter.Unlock()
	return mock.SetProjectParameterFunc(projectID, name, value, secure)
}

// SetProjectParameterCalls gets all the calls that were made to SetProjectParameter.
// Check the length with:
//
//	len(mockedClientInterface.SetProjectParameterCalls())
func (mock *ClientInterfaceMock) SetProjectParameterCalls() []struct {
	ProjectID string
	Name      string
	Value     string
	Secure    bool
} {
	var calls []struct {
		ProjectID string
		Name      string
		Value     string
		Secure    bool
	}
	mock.lockSetProjectParameter.RLock()
	calls = mock.calls.SetProjectParameter
	mock.lockSetProjectParameter.RUnlock()
	return calls
}

// SetQueuedBuildPosition calls SetQueuedBuildPositionFunc.
func (mock *ClientInterfaceMock) SetQueuedBuildPosition(buildID string, position int) error {
	if mock.SetQueuedBuildPositionFunc == nil {
		panic("ClientInterfaceMock.SetQueuedBuildPositionFunc: method is nil but ClientInterface.SetQueuedBuildPosition was just called")
	}
	callInfo := struct {
		BuildID  string
		Position int
	}{
		BuildID:  buildID,
		Position: position,
	}
	mock.lockSetQueuedBuildPosition.Lock()
	mock.calls.SetQueuedBuildPosition = append(mock.calls.SetQueuedBuildPosition, callInfo)
	mock.lockSetQueuedBuildPosition.Unlock()
	return mock.SetQueuedBuildPositionFunc(buildID, position)
}

// SetQueuedBuildPositionCalls gets all the calls that were made to SetQueuedBuildPosition.
// Check the length with:
//
//	len(mockedClientInterface.SetQueuedBuildPositionCalls())
func (mock *ClientInterfaceMock) SetQueuedBuildPositionCalls() []struct {
	BuildID  string
	Position int
} {
	var calls []struct {
		BuildID  string
		Position int
	}
	mock.lockSetQueuedBuildPosition.RLock()
	calls = mock.calls.SetQueuedBuildPosition
	mock.lockSetQueuedBuildPosition.RUnlock()
	return calls
}

// SupportsFeature calls SupportsFeatureFunc.
func (mock *ClientInterfaceMock) SupportsFeature(feature string) bool {
	if mock.SupportsFeatureFunc == nil {
		panic("ClientInterfaceMock.SupportsFeatureFunc: method is nil but ClientInterface.SupportsFeature was just called")
	}
	callInfo := struct {
		Feature string
	}{
		Feature: feature,
	}
	mock.lockSupportsFeature.Lock()
	mock.calls.SupportsFeature = append(mock.calls.SupportsFeature, callInfo)
	mock.lockSupportsFeature.Unlock()
	return mock.SupportsFeatureFunc(feature)
}

// SupportsFeatureCalls gets all the calls that were made to SupportsFeature.
// Check the length with:
//
//	len(mockedClientInterface.SupportsFeatureCalls())
func (mock *ClientInterfaceMock) SupportsFeatureCalls() []struct {
	Feature string
} {
	var calls []struct {
		Feature string
	}
	mock.lockSupportsFeature.RLock()
	calls = mock.calls.SupportsFeature
	mock.lockSupportsFeature.RUnlock()
	return calls
}

// UnpinBuild calls UnpinBuildFunc.
func (mock *ClientInterfaceMock) UnpinBuild(buildID string) error {
	if mock.UnpinBuildFunc == nil {
		panic("ClientInterfaceMock.UnpinBuildFunc: method is nil but ClientInterface.UnpinBuild was just called")
	}
	callInfo := struct {
		BuildID string
	}{
		BuildID: buildID,
	}
	mock.lockUnpinBuild.Lock()
	mock.calls.UnpinBuild = append(mock.calls.UnpinBuild, callInfo)
	mock.lockUnpinBuild.Unlock()
	return mock.UnpinBuildFunc(buildID)
}

// UnpinBuildCalls gets all the calls that were made to UnpinBuild.
// Check the length with:
//
//	len(mockedClientInterface.UnpinBuildCalls())
func (mock *ClientInterfaceMock) UnpinBuildCalls() []struct {
	BuildID string
} {
	var calls []struct {
		BuildID string
	}
	mock.lockUnpinBuild.RLock()
	calls = mock.calls.UnpinBuild
	mock.lockUnpinBuild.RUnlock()
	return calls
}

// UserExists calls UserExistsFunc.
func (mock *ClientInterfaceMock) UserExists(username string) bool {
	if mock.UserExistsFunc == nil {
		panic("ClientInterfaceMock.UserExistsFunc: method is nil but ClientInterface.UserExists was just called")
	}
	callInfo := struct {
		Username string
	}{
		Username: username,
	}
	mock.lockUserExists.Lock()
	mock.calls.UserExists = append(mock.calls.UserExists, callInfo)
	mock.lockUserExists.Unlock()
	return mock.UserExistsFunc(username)
}

// UserExistsCalls gets all the calls that were made to UserExists.
// Check the length with:
//
//	len(mockedClientInterface.UserExistsCalls())
func (mock *ClientInterfaceMock) UserExistsCalls() []struct {
	Username string
} {
	var calls []struct {
		Username string
	}
	mock.lockUserExists.RLock()
	calls = mock.calls.UserExists
	mock.lockUserExists.RUnlock()
	return calls
}
